# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_sale_payment_method_alter_client_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
