# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="measurement_unit",
            field=models.CharField(
                blank=True,
                choices=[("jardas", "Jardas"), ("metros", "Metros")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("standard", "Produto"), ("line", "Linha")],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_measure_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_piece_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
            ),
        ),
    ]
